.\"	$Id$
.\"
.\" Copyright notice goes here.
.\"
.\" See mdoc(7) for further reference.
.\"
.Dd $Mdocdate$
.\" Replace the following with the name of your library/function in
.\" UPPERCASE.
.Dt LIBRARYNAME 3
.Os
.Sh NAME
.\" If a single function, have only one `Nm'.
.\" If a library with many functions, have the library first followed by
.\" functions with a trailing comma (except for the last).
.Nm libraryname ,
.Nm function0 ,
.Nm function1
.Nd one-liner without punctuation
.Sh SYNOPSIS
.\" Any header files?
.In header.h
.\" Any global variables?
.Vt extern int foo;
.\" Functions.
.Ft "int"
.Fo function0
.Fa "int arg0"
.Fc
.Ft "void"
.Fo function1
.Fa "const char * arg1"
.Fc
.Sh DESCRIPTION
The
.Nm
library does this and that.
.\" Do you have any variables?  Document them here.
.Ss Variables
Variable descriptions follow:
.Bl -ohang
.It Va foo
What is this?
.El
.\" Do you have any functions?  Document them here.
.Ss Functions
Function descriptions follow:
.Bl -ohang
.It Fn function0
What does this do?
.El
.Sh RETURN VALUES
.Rv -std
.Sh EXAMPLES
Give us some examples.
.Sh SEE ALSO
.\" Does anybody use these functions?  Did you refer to anything?
.Xr foobar 1
.Sh AUTHORS
The
.Nm
utility was written by
.\" Enter your contact information here.
.An yourname Aq you@domain.tdl .
