.\"	$Id$
.\"
.\" Copyright notice goes here.
.\"
.\" See mdoc(7) for further reference.
.\"
.Dd $Mdocdate$
.\" Replace the following with the name of your utility in UPPERCASE.
.Dt UTILITYNAME 1
.Os
.
.Sh NAME
.\" Replace the following two lines as indicated.
.Nm utilityname
.Nd one-liner without punctuation
.Sh SYNOPSIS
.Nm
.\" Add your utility's flags and arguments.
.Op Fl optional_flags
.Op Fl optional_flag Ar with_arg
.Op Ar optional_args
.Ar required_args
.Sh DESCRIPTION
The
.Nm
utility does this and that. \" Remember: end-of-sentence, end-of-line!
.\" Document its arguments first.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl flag
Document each flag separately.
.It Fl flag Ar arg
Document each flag/argument separately.
.It Ar arg
Document each argument separately.
.El
.Pp
By default, the
.Nm
utility does this and that.
.Sh EXIT STATUS
.\" Change this if it's not the case.
.Ex -std
.Sh SEE ALSO
.\" What other utilities have you referred to?
.Xr foobar 1
.Sh AUTHORS
The
.Nm
utility was written by
.\" Enter your contact information here.
.An yourname Aq you@domain.tdl .
